### ISSUE TITLE
[ASTextNode] ASTextKitRenderer not always invalidated when needed.

### ISSUE THREAD

**Issue by timominous** [facebook/AsyncDisplayKit#1046]
After updating to 1.9.4, my single character text node is being rendered incomplete.

Before:
![before](https://cloud.githubusercontent.com/assets/733151/12192113/ed2cb612-b616-11e5-96e1-3abaaffaf3ca.PNG)
After:
![after](https://cloud.githubusercontent.com/assets/733151/12192116/f885038e-b616-11e5-9126-e6e799fb0468.PNG)

We can see from the dark gray area that the size is calculated correctly but the text isn't rendered properly.

I am experiencing this when the supernode (custom `ASCellNode` subclass) was just initialized by `-tableView:nodeForRowAtIndexPath:` and is displayed immediately. After scrolling up and down for a few times, the rendering of the text will appear completed.

I'm really new to AsyncDisplayKit so I'm not sure if this has something to do with my code or the framework's code.

**Comment by bsmith11** [comment]
#1031 

Getting the same behavior. Seems to only happen when `alignment = NSTextAlignmentCenter`.

**Comment by AttilaTheFun** [comment]
I'm having this issue as well with a text node inside a horizontal stack layout spec.

**Comment by nvh** [comment]
I'm having this issue as well, and have narrowed it down to the invalidation of the renderer in the text node, specifically in the line that is highlighted here:
https://github.com/facebook/AsyncDisplayKit/commit/1872ac07aa7f4c03678d6b00aa6f183514599acd#diff-221147908d17673747bdcbd88905332cR312
When YES is returned instead of NO here (invalidating the renderer for this case) The text is rendered as expected.

**Comment by appleguy** [comment]
@nvh thanks for looking at this - what version of ASDK are you running on?  It looks like a commit from mid-December, and I think this issue was fixed shortly after that...it should be in 1.9.3-1.9.5 I think.  I believe the initial regression of this was in 1.9.2.

@timominous what version of ASDK are /you/ running on?  :)

**Comment by appleguy** [comment]
@nguyenhuy, @samhsiung if you have a chance to take a look in the next day or two — please do!  The 6 month plan review is tomorrow, so I'm pretty jammed until late Wednesday or around the end of the week.  But this could be a bug important enough to do a hotfix for, if somehow we've missed detecting it previously.

**Comment by nguyenhuy** [comment]
Will take a look as soon as I can :)

**Comment by nvh** [comment]
For the record: I've encountered this issue while upgrading from 1.9.3 to 1.9.4, and am still experiencing it in 1.9.5

**Comment by appleguy** [comment]
@nvh @timominous @AttilaTheFun @bsmith11 @nguyenhuy thankfully I am quite confident this is conclusively fixed by #1100.  Please test and report any text bugs you see.  Finally, I believe we have addressed all of the known issues here since the ComponentKit updates were merged in.
