### ISSUE TITLE
[ASPagerNode] Address crash from rotation support in custom collection view layout.

### ISSUE THREAD

**Issue by cc-lam** [facebook/AsyncDisplayKit#1372]
Tapping the `reload` button crashes the application

**Comment by hannahmbanana** [comment]
I have the same issue. When running the example with ASDK 1.9.7 on an actual device, the crash manifests itself as this weird layout upon reload: 

![img_2840](https://cloud.githubusercontent.com/assets/3419380/13769299/c51302b8-ea3b-11e5-800b-29b508bbd1ef.PNG)

When running in the simulator, it is also 100% reproducible for me. 

![screen shot 2016-03-14 at 11 27 59 pm](https://cloud.githubusercontent.com/assets/3419380/13769397/7a881db8-ea3c-11e5-9234-edcd4248f893.png)

It looks like it's a divide by zero in **ASPagerFlowLayout's** layoutAttributesForItemAtIndexPath: message to UICollectionViewLayout. 

(lldb) po self.currentIndexPath
<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}
(lldb) p proposedContentOffset
(CGPoint) $1 = (x = 0, y = 0)

If I comment out the call to  _targetContentOffsetForItemAtIndexPath: in the method above, so that it just return's a call to the super targetContentOffsetForProposedContentOffset: then it appears to work. 

It looks like this might be a known issue? http://stackoverflow.com/questions/13511733/how-to-make-supplementary-view-float-in-uicollectionview-as-section-headers-do-i

The reload button works in commit c1ca225e8dcf789d1c4f1c1c7e4624ae46ff399c, but not in commit 66c8c8f47d6b1b4d112a579ab0636949ead4d956 after rotation support was added to ASPagerNode.

**Comment by levi** [comment]
Thanks for the stack trace, @hannahmbanana. I actually have rewriting the calculation of the contentOffset on my list this week. The new approach should fix this issue.

**Comment by appleguy** [comment]
@levi let me know if I can help with this. Although the 1.9.7 tag has already been cut and updated a few times, I still have not announced it, but would love to do so soon. If we are fairly confident that this issue would not affect most applications, I am happy to send out the post later this weekend. Otherwise is fine to wait for next week to investigate.

**Comment by appleguy** [comment]
@cc-lam thank you for reporting this, and thanks @hannahmbanana for investigating!  @levi delivered the goods with the fix, and it would be great if folks could retest.  Please reopen or file a new task if you see any other issues.

https://github.com/facebook/AsyncDisplayKit/pull/1418

**Comment by appleguy** [comment]
Looks like this isn't fully resolved - pinged Levi with new details, we'll get it wrapped up in the next day or so.

**Comment by appleguy** [comment]
This has been resolved for the past couple weeks, please let me know if you encounter any other issues.
