### ISSUE TITLE
During layout transition, initialFrameForNode and finalFrameForNode are the same

### ISSUE THREAD

**Issue by jellenbogen** [facebook/AsyncDisplayKit#1387]
@levi I was testing out the new layoutSpec transitions in my app and was modeling my code off the example you've created for the animated form. However when I come to animateLayoutTransition in my example app, initialFrameForNode and finalFrameForNode return the same value from the supplied ASContextTransitioning.

I was stepping through the code and it looks like when calling transitionLayoutWithSizeRange, the first thing that is done is to iterate through all the subnodes and set the following:

```
ASDisplayNodePerformBlockOnEverySubnode(self, ^(ASDisplayNode * _Nonnull node) {
    ASDisplayNodeAssert([node _hasTransitionsInProgress] == NO, @"Can't start a transition when one of the subnodes is performing one.");
    node.hierarchyState |= ASHierarchyStateLayoutPending;
    node.pendingTransitionID = transitionID;
});
```

Then immediately following this the newLayout is created, which I assume is the layout that takes into consideration all state changes that have happened and is where finalFrameForNode gets its values. The issue I'm seeing is that the newLayout calls this in the transitionBlock:

```
newLayout = [self calculateLayoutThatFits:constrainedSize];
```

But when going through this pass of calculateLayoutThatFits, calling measureWithSizeRange on each subnode does nothing since we have just set the hierarchyState and pendingTransactionID on each subnode. So measureWithSizeRange fails when checking:

```
if (ASHierarchyStateIncludesLayoutPending(_hierarchyState) && constrainedSize.transitionID != _pendingTransitionID) {
    return NO;
}
```

So my question is am I doing something wrong here or should measureWithSizeRange always perform a measurement in the case where it is called in calculateLayoutThatFits via transitionLayoutWithAnimation?

I've attached the code for a test app I created just to show just this one example. If you or anyone else has a moment to take a look that'd be awesome, maybe something will stand out for you that I'm just missing. Either way I appreciate any help I can get!

[LayoutTransitionTestApp.zip](https://github.com/facebook/AsyncDisplayKit/files/175674/LayoutTransitionTestApp.zip)

**Comment by jellenbogen** [comment]
What I was thinking is, should this block:

```
ASDisplayNodePerformBlockOnEverySubnode(self, ^(ASDisplayNode * _Nonnull node) {
	ASDisplayNodeAssert([node _hasTransitionsInProgress] == NO, @"Can't start a transition when one of the subnodes is performing one.");
	node.hierarchyState |= ASHierarchyStateLayoutPending;
	node.pendingTransitionID = transitionID;
});
```
come after this block:

```
ASLayout *newLayout;
{
  ASDN::MutexLocker l(_propertyLock);
  BOOL disableImplicitHierarchyManagement = self.usesImplicitHierarchyManagement == NO;
  self.usesImplicitHierarchyManagement = YES; // Temporary flag for 1.9.x
  newLayout = [self calculateLayoutThatFits:constrainedSize];
  if (disableImplicitHierarchyManagement) {
    self.usesImplicitHierarchyManagement = NO; // Temporary flag for 1.9.x
  }
}
```

In transitionLayoutWithSizeRange, when I tried making this change I was seeing the values I was expecting to see where the new layout is getting the correct finalValues.

**Comment by appleguy** [comment]
@levi @nguyenhuy @maicki

**Comment by nguyenhuy** [comment]
@jellenbogen Thanks for this detailed report. I ran your sample and found out that stack spec doesn't pass along transition ID to its children (https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Private/ASStackUnpositionedLayout.mm#L32). This causes subnodes (`banner` node in your example) to refuse to measure because the constrained size given to each of them doesn't contain the transition ID they are expecting.

Because of the above reason, I still believe the call order in `transitionLayoutWithSizeRange:animated:shouldMeasureAsync:measurementCompletion` is valid. @appleguy and I have a fix and will put up a PR in a few days. Please be patient. Thank you!

**Comment by jellenbogen** [comment]
@nguyenhuy I see that makes sense. Thanks for taking a look!

**Comment by jellenbogen** [comment]
@nguyenhuy Is there an issue tracking the fact that the transition ID is not being passed along to the children?

**Comment by nguyenhuy** [comment]
There isn't a ticket on GitHub but we're actively working on it.

**Comment by nguyenhuy** [comment]
@jellenbogen This should be fixed by #1443. Let me know if you still hit this problem.

**Comment by appleguy** [comment]
@jellenbogen - have you had a chance to see if this resolves your issue?

**Comment by jellenbogen** [comment]
I haven't I was planning on testing this, this weekend.
On Wed, Mar 30, 2016 at 10:29 PM appleguy <notifications@github.com> wrote:

> @jellenbogen <https://github.com/jellenbogen> - have you had a chance to
> see if this resolves your issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/AsyncDisplayKit/issues/1387#issuecomment-203759057>
>
-- 
Thanks,
Jonathan

**Comment by appleguy** [comment]
@jellenbogen: Thanks for reporting this issue! From our side, it appears that this issue has been resolved. Please reopen this if PR #1443 does not resolve your issue.
