### ISSUE TITLE
Gif not animated in master branch for sample ASAnimatedImage

### ISSUE THREAD

**Issue by xiaomaogong** [facebook/AsyncDisplayKit#2769]
After i upgrade the AsyncDisplaykit from 1.9.81 to 2.0(or latest master branch) , looks like the gif is not working anymore.

Below is issue screenshot that looks like only show first frame of this gif
![simulator screen shot 14 dec 2016 3 28 08 pm](https://cloud.githubusercontent.com/assets/9329201/21173490/ea6822f0-c212-11e6-9de1-bf02356d6325.png)

Also in 1.9.82 , the gif will overlap the image node like below , which is why i try to solve it by upgrading AsyncDisplayKit version.

The code is:

```
ASNetworkImageNode *imageNode = [[ASNetworkImageNode alloc] init];
  imageNode.URL = [NSURL URLWithString:@"https://s-media-cache-ak0.pinimg.com/originals/07/44/38/074438e7c75034df2dcf37ba1057803e.gif"];
    imageNode.frame = CGRectMake(50, 50, 200, 200);
    imageNode.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    imageNode.contentMode = UIViewContentModeScaleAspectFill;
    imageNode.borderWidth = 2;
    imageNode.borderColor = [[UIColor blackColor] CGColor];

  [self.view addSubnode:imageNode];

```

![simulator screen shot 14 dec 2016 2 36 22 pm](https://cloud.githubusercontent.com/assets/9329201/21173524/1c080988-c213-11e6-8e0f-dbd1f48afd74.png)

**Comment by xiaomaogong** [comment]
After debugging into the code i found that the animatedImage property on ASNetworkImageNode will be set to nil in latest master branch , which is not the case in 1.9.82

```
#pragma mark - Public methods -- must lock

/// Setter for public image property. It has the side effect to set an internal _imageWasSetExternally that prevents setting an image internally. Setting an image internally should happen with the _setImage: method
- (void)setImage:(UIImage *)image
{
  ASDN::MutexLocker l(__instanceLock__);
  
  _imageWasSetExternally = (image != nil);
  if (_imageWasSetExternally) {
    [self _cancelDownloadAndClearImage];
    _URL = nil;
  }
  
  [self _setImage:image];
}
```

 Above is the  setImage: method in ASNetworkImageNode that override setImage: in ASImageNode,  
and  [self _cancelDownloadAndClearImage]; will clear the animatedImage , is that the reason why the gif can't play correctly anymore?

**Comment by maundytime** [comment]
Hi xiaomaogong, did you fix this problem?

**Comment by xiaomaogong** [comment]
NO. I still can't load gif in latest version.

**Comment by maundytime** [comment]
@xiaomaogong  I found the sample project AnimatedGIF worked fine on simulator, but did not work on my device. I mention in #2831 . Have you tried to run your project on simulator?

**Comment by christianselig** [comment]
Having issues with this myself as well.

**Comment by xiaomaogong** [comment]
Looks like its working in 2.1 version now , will close it

**Comment by davitPiloyan93** [comment]
The issue persists for ios 9 versions.
Here is a link to a small sample app that reproduces the issue:
https://drive.google.com/file/d/0B05hQ25cGDZydXRXa2xGZHBEOUU/view?usp=sharing

**Comment by mikengyn** [comment]
Still broken for me but worked randomly in some instances.

**Comment by garrettmoon** [comment]
@mikengyn it's fixed in PINRemoteImage if you include master. I'll do a release there soon and then we'll bundle it up in ASDK. Likely 2.1.1

**Comment by jeffdav** [comment]
@garrettmoon That'd be swell.  Thanks.

**Comment by phuson** [comment]
@davitPiloyan93 I tried running your sample app and tried it with an HTTPS resource instead and it works fine for me. https://media.giphy.com/media/l0Ex3vQtX5VX2YtAQ/source.gif

**Comment by davitPiloyan93** [comment]
@phuson I check this url https://media.giphy.com/media/l0Ex3vQtX5VX2YtAQ/source.gif
in my device,but still cannot load gif.
My device iphone 6s version 9.3.3

**Comment by phuson** [comment]
@davitPiloyan93 Ahh, that's odd. You might want to also try what @garrettmoon suggested above (https://github.com/facebook/AsyncDisplayKit/issues/2769#issuecomment-278460946). It works great for me.

**Comment by davitPiloyan93** [comment]
@phuson Thanks

**Comment by xiaomaogong** [comment]
@garrettmoon This issue does still exist in 2.1 , the reason why i found its resolved is because that I have the gif cache for working version(1.9.81).

Anyway , I'm very glad to heard that it will be fixed in next release version.
