### ISSUE TITLE
[ASTextNode] doesn't apply the link color and NSUnderlineStyleNone style

### ISSUE THREAD

**Issue by freeant** [facebook/AsyncDisplayKit#822]
The ASTextNode didn't apply the link color and underline style with NSUnderlineStyleNone. It's aways keep blue color and have underline. It's that I miss some thing?

 NSURL *url = [NSURL URLWithString:[NSString stringWithFormat:@"user://%@",u[@"objectId"]]];
                    [body addAttributes:@{
                                          NSForegroundColorAttributeName:kAtNameColor,
                                          NSLinkAttributeName:url,
                                          NSUnderlineStyleAttributeName:@(NSUnderlineStyleNone)
                                          } range:range];

**Comment by appleguy** [comment]
@levi, could you check this out since you've been in ASTextNode recently?  Make sure we don't break ASDK link handling with the CK renderer...

**Comment by levi** [comment]
Interesting. I'll check this out this week.

**Comment by bsmith11** [comment]
Any update on this? I'm having the same problem

**Comment by appleguy** [comment]
@freeant @bsmith11 - could you try this out on the latest master and let me know if it works? I believe there are some changes that may have resolved this, but I haven't had time to try it myself yet.

**Comment by appleguy** [comment]
@freeant @bsmith11: thanks for contributing to the AsyncDisplayKit community by reporting this bug. Due to the length of time it’s been since this thread was active and the fact that I believe this has been resolved on master since then, I’m going to mark this issue as closed. If you are still having troubles, feel free to reopen it. I hope you have been able to use the framework!

**Comment by logicsb** [comment]
I Have the same issue. When apply an color in Text Link the text appears with color, but underline with blue. When try set `[NSUnderlineStyleAttributeName: NSUnderlineStyle.StyleNone.rawValue]` this is ignored and blue underline don't disappear.

**Comment by ocrickard** [comment]
These link colors are being added by the underlying TextKit objects. I'm surprised it is overriding your specification though.

What happens if you use NSUnderlineColorAttributeName and use a different color? Does it pick that up?

**Comment by logicsb** [comment]
Hi @ocrickard. Yes NSUnderlineColorAttributeName work's fine. But i need remove the underline. I've make a workaround with UIColor.clearColor() because NSUnderlineStyleAttributeName is not working. Thanks.

**Comment by ocrickard** [comment]
Cool, sadly if TextKit is adding the underline and overriding that value doesn't fix it then there is little we can do here besides file a radar.
