### ISSUE TITLE
ASTextNode doesn't render NSAttributedString properly when style.alignment = NSTextAlignmentCenter;

### ISSUE THREAD

**Issue by aaronschubert0** [facebook/AsyncDisplayKit#89]
See:
![screen shot 2014-11-05 at 14 18 53](https://cloud.githubusercontent.com/assets/9281756/4919053/ce75bd26-64f6-11e4-87e5-6a354ab5922d.png)

**Comment by mtitolo** [comment]
+1 this is a problem for us.

In addition: When the text is only 1 line, it's not shown at all.

Code to reproduce:
```
    NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
    paragraphStyle.alignment = NSTextAlignmentCenter;
    
    NSDictionary *attributes = @{
                                 NSForegroundColorAttributeName: [UIColor whiteColor],
                                 NSFontAttributeName: [UIFont systemFontOfSize:17],
                                 NSParagraphStyleAttributeName: paragraphStyle,
                                 };
    NSAttributedString *testString = [[NSAttributedString alloc] initWithString:@"This is a test." attributes:attributes];
    text.attributedString = testString;
    [text measure:CGSizeMake(self.view.frame.size.width, 21)];
    text.frame = CGRectMake(200, 300, text.calculatedSize.width, text.calculatedSize.height);
    [self.view addSubview:text.view];
```

**Comment by ocrickard** [comment]
OK, yep, definitely a bug, just repro'd locally and have a fix I'll put up in a minute.  However, we should note that this kills one of our optimizations, but in the name of correctness I'm happy we found it!  Thanks for reporting.

**Comment by secretiverhyme** [comment]
Fixed in #329.

**Comment by nivanchikov** [comment]
@ocrickard, @secretiverhyme 
I faced the alignment issue after the fix was introduced in #329.

![img_0324](https://cloud.githubusercontent.com/assets/1830010/6493524/e6c2dba4-c2c3-11e4-8046-b3caf0e4fe88.PNG)


Here's my setup  

```objc
- (instancetype) initWithUser: (SMUser*) user
{
	if (self = [super init])
	{
		self.displaysAsynchronously = NO;
		self.backgroundColor = [UIColor whiteColor];

		self.nameTextNode = (
		{
			NSAttributedString* text = nil;

			if ([user.fullName length])
				text = [[NSAttributedString alloc] initWithString: user.fullName
													   attributes: [SMDirSpecialistCellNode _nameTextAttributes]];

			ASTextNode* node = [ASTextNode new];

			node.layerBacked = YES;
			node.attributedString = text;
			node.backgroundColor = [UIColor greenColor];

			[self addSubnode: node];
			node;
		});

// and two other labels with same setup
	}

	return self;
}


#pragma mark -
#pragma mark Layout


- (CGSize) calculateSizeThatFits: (CGSize) constrainedSize
{
	CGFloat width = constrainedSize.width - 40.0f;

	CGFloat topOffsetY = 20.0f; //130.0f;

	CGFloat height = topOffsetY;

	if ([_nameTextNode.attributedString length])
	{
		[_nameTextNode measure: CGSizeMake(width, CGFLOAT_MAX)];
		CGSize size = [_nameTextNode frameForTextRange: NSMakeRange(0, _nameTextNode.attributedString.length)].size;
		height += ceilfCGSize(size).height;
	}

	if ([_positionTextNode.attributedString length])
	{
		[_positionTextNode measure: CGSizeMake(width, CGFLOAT_MAX)];
		CGSize size = [_positionTextNode frameForTextRange: NSMakeRange(0, _positionTextNode.attributedString.length)].size;
		height += ceilfCGSize(size).height;
	}

	if ([_bioTextNode.attributedString length])
	{
		[_bioTextNode measure: CGSizeMake(width, CGFLOAT_MAX)];
		CGSize size = [_bioTextNode frameForTextRange: NSMakeRange(0, _bioTextNode.attributedString.length)].size;
		height += ceilfCGSize(size).height;
	}

	height += 20.0f; //115.0f;

	return CGSizeMake(constrainedSize.width, height);
}


- (void) layout
{
	CGFloat width = self.calculatedSize.width;

	CGFloat offsetY = 20.0f; //130.0f;

	_nameTextNode.frame = (CGRect){CGPointMake((width - _nameTextNode.calculatedSize.width) / 2.0f, offsetY),
			_nameTextNode.calculatedSize};

	_positionTextNode.frame = (CGRect){CGPointMake((width - _positionTextNode.calculatedSize.width) / 2.0f,
			CGRectGetMaxY(_nameTextNode.frame)), _positionTextNode.calculatedSize};

	_bioTextNode.frame = (CGRect){CGPointMake((width - _bioTextNode.calculatedSize.width) / 2.0f,
			CGRectGetMaxY(_positionTextNode.frame)), _bioTextNode.calculatedSize};
}


#pragma mark -
#pragma mark Text attributes


+ (NSDictionary*) _nameTextAttributes
{
	NSMutableParagraphStyle* style = [NSMutableParagraphStyle new];
	style.alignment = NSTextAlignmentCenter;


	return @{NSForegroundColorAttributeName : [UIColor colorFromHex: 0x222222 alpha: 1.0f],
			NSFontAttributeName : [UIFont helveticaNeueWithWeight: FontWeightMedium height: 26.0f],
			NSParagraphStyleAttributeName : style};
}
```


What I've noticed is that `- (void)setBounds:(CGRect)bounds` is not called on `ASTextNode`, so the fix does not apply. I assume it happens because the node has a layer, here's an excerpt from `- (void)setFrame:(CGRect)rect` for `ASDisplayNode`:


```objc
- (void)setFrame:(CGRect)rect
{
  _bridge_prologue;

  // Frame is only defined when transform is identity because we explicitly diverge from CALayer behavior and define frame without transform
#if DEBUG
  // Checking if the transform is identity is expensive, so disable when unnecessary. We have assertions on in Release, so DEBUG is the only way I know of.
  ASDisplayNodeAssert(CATransform3DIsIdentity(self.transform), @"Must be an identity transform");
#endif

  if (_layer && ASDisplayNodeThreadIsMain()) {
// THIS BRANCH GETS CALLED ON SETTING A FRAME ON ASTEXTNODE
    CGPoint anchorPoint = _layer.anchorPoint;
    _layer.bounds = CGRectMake(0, 0, rect.size.width, rect.size.height);
    _layer.position = CGPointMake(rect.origin.x + rect.size.width * anchorPoint.x,
                                 rect.origin.y + rect.size.height * anchorPoint.y);
  } else {
    CGPoint anchorPoint = self.anchorPoint;
    self.bounds = CGRectMake(0, 0, rect.size.width, rect.size.height);
    self.position = CGPointMake(rect.origin.x + rect.size.width * anchorPoint.x,
                                rect.origin.y + rect.size.height * anchorPoint.y);
  }
}

```


So I tried to override `- (void)setFrame:(CGRect)rect` on `ASTextNode` instead of  `- (void)setBounds:(CGRect)bounds` and it gave the result I was looking for (with same code as @ocrickard suggested):


```objc
- (void) setFrame: (CGRect) frame
{
	[super setFrame: frame];

	if (!CGSizeEqualToSize(frame.size, _constrainedSize)) {
		// Our bounds have changed to a size that is not identical to our constraining size,
		// so our previous layout information is invalid, and TextKit may draw at the
		// incorrect origin.
		_constrainedSize = CGSizeMake(-INFINITY, -INFINITY);
		[self _invalidateRenderer];
	}
}
```

Result:
![img_0325](https://cloud.githubusercontent.com/assets/1830010/6493784/ad746186-c2c5-11e4-84e1-79f5a5d8fdbd.PNG)


So I wanted to ask whether that is a vital solution or not?

**Comment by mtitolo** [comment]
Also still seeing this after the fix was applied.

**Comment by ocrickard** [comment]
@nivanchikov good point on setFrame.  We should also probably implement setFrame in addition to setBounds.  Pull request would be awesome!

Re the bridge being the fault: yes, I believe you're probably right.  If we implement both it should allow us to circumvent that issue though.

**Comment by adcooley** [comment]
hey everyone, this is still an issue for me. Specifically, I'm on the `1.9.4` release and this is specific to ASTextNodes added to ASCellNodes. Anyone else seeing this again?

**Comment by gauravmnit07** [comment]
I'm also seeing this issue while rendering text node in cell nodes. Any solution will be highly appreciated.
Thanks.

**Comment by EviluS** [comment]
@gauravmnit07 try downgrading to 1.9.3. This problem also appeared to me when I to 1.9.5.

**Comment by aaronschubert0** [comment]
@EviluS @gauravmnit07 1.9.6 should actually have fixed these issues, so it's best to upgrade to that version.

**Comment by gauravmnit07** [comment]
@aaronschubert0 Yes it's working fine after updating to 1.9.6. Thanks for the update.
